site_name: 'python-app-11'
site_description: 'Main documentation for the python-app-11'
repo_url: https://github.com/thanhlam2396/python-app-11
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:

      - Getting started: 'docs/index.md'
